# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ArchivosForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ArchivosForm(object):
    def setupUi(self, ArchivosForm):
        ArchivosForm.setObjectName("ArchivosForm")
        ArchivosForm.resize(711, 582)
        ArchivosForm.setStyleSheet("")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(ArchivosForm)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Container = QtWidgets.QFrame(ArchivosForm)
        self.Container.setStyleSheet("QFrame#Container{\n"
"    background-color: #7D211A;\n"
"    border-radius: 10px;\n"
"}")
        self.Container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Container.setObjectName("Container")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Container)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.ContVerticalLayout = QtWidgets.QVBoxLayout()
        self.ContVerticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.ContVerticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.ContVerticalLayout.setObjectName("ContVerticalLayout")
        self.Titulo = QtWidgets.QLabel(self.Container)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Titulo.setFont(font)
        self.Titulo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Titulo.setStyleSheet("color: white;")
        self.Titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.Titulo.setObjectName("Titulo")
        self.ContVerticalLayout.addWidget(self.Titulo)
        self.widget = QtWidgets.QWidget(self.Container)
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(1, 9, 631, 109))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TituloDatosPrincipales = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TituloDatosPrincipales.sizePolicy().hasHeightForWidth())
        self.TituloDatosPrincipales.setSizePolicy(sizePolicy)
        self.TituloDatosPrincipales.setBaseSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.TituloDatosPrincipales.setFont(font)
        self.TituloDatosPrincipales.setStyleSheet("color: white;")
        self.TituloDatosPrincipales.setObjectName("TituloDatosPrincipales")
        self.verticalLayout_2.addWidget(self.TituloDatosPrincipales)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(16, -1, -1, -1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelPrincipal = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.labelPrincipal.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelPrincipal.setFont(font)
        self.labelPrincipal.setStyleSheet("font-size: 14pt;\n"
"color:white;\n"
"background-color: #EF8903;\n"
"padding: 0 12px;\n"
"border-radius: 12px;\n"
"max-height: 32px;")
        self.labelPrincipal.setText("")
        self.labelPrincipal.setObjectName("labelPrincipal")
        self.horizontalLayout_2.addWidget(self.labelPrincipal)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.btnDatosPrincipales = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnDatosPrincipales.setFont(font)
        self.btnDatosPrincipales.setStyleSheet("QPushButton{\n"
"background-color: #BABABA;\n"
"padding: 5px;\n"
"max-width: 150px;\n"
"border-style: outset;\n"
"border-radius: 15px;\n"
"color:  #373737;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #878787;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #121212;\n"
"    color: white;\n"
"}\n"
"\n"
"")
        self.btnDatosPrincipales.setObjectName("btnDatosPrincipales")
        self.verticalLayout_2.addWidget(self.btnDatosPrincipales)
        self.ContVerticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.Container)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.widget_2)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(1, 9, 631, 118))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.TituloDatosPrincipales_5 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TituloDatosPrincipales_5.sizePolicy().hasHeightForWidth())
        self.TituloDatosPrincipales_5.setSizePolicy(sizePolicy)
        self.TituloDatosPrincipales_5.setBaseSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.TituloDatosPrincipales_5.setFont(font)
        self.TituloDatosPrincipales_5.setStyleSheet("color: white;")
        self.TituloDatosPrincipales_5.setObjectName("TituloDatosPrincipales_5")
        self.verticalLayout_6.addWidget(self.TituloDatosPrincipales_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(16, -1, 16, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelAdicional = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        self.labelAdicional.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelAdicional.setFont(font)
        self.labelAdicional.setStyleSheet("font-size: 14pt;\n"
"color:white;\n"
"background-color: #EF8903;\n"
"padding: 0 12px;\n"
"border-radius: 12px;\n"
"max-height: 32px;\n"
"")
        self.labelAdicional.setText("")
        self.labelAdicional.setObjectName("labelAdicional")
        self.horizontalLayout_4.addWidget(self.labelAdicional)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_6.addLayout(self.horizontalLayout_4)
        self.btnDatosAdicionales = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnDatosAdicionales.setFont(font)
        self.btnDatosAdicionales.setStyleSheet("QPushButton{\n"
"background-color: #BABABA;\n"
"padding: 5px;\n"
"max-width: 150px;\n"
"border-style: outset;\n"
"border-radius: 15px;\n"
"color:  #373737;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #878787;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #121212;\n"
"    color: white;\n"
"}\n"
"\n"
"")
        self.btnDatosAdicionales.setObjectName("btnDatosAdicionales")
        self.verticalLayout_6.addWidget(self.btnDatosAdicionales)
        self.ContVerticalLayout.addWidget(self.widget_2)
        self.MapasWidget = QtWidgets.QWidget(self.Container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.MapasWidget.sizePolicy().hasHeightForWidth())
        self.MapasWidget.setSizePolicy(sizePolicy)
        self.MapasWidget.setObjectName("MapasWidget")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.MapasWidget)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(1, 9, 631, 128))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.TituloDatosPrincipales_6 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TituloDatosPrincipales_6.sizePolicy().hasHeightForWidth())
        self.TituloDatosPrincipales_6.setSizePolicy(sizePolicy)
        self.TituloDatosPrincipales_6.setBaseSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.TituloDatosPrincipales_6.setFont(font)
        self.TituloDatosPrincipales_6.setStyleSheet("color: white;")
        self.TituloDatosPrincipales_6.setObjectName("TituloDatosPrincipales_6")
        self.verticalLayout_7.addWidget(self.TituloDatosPrincipales_6)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(16, -1, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.labelMapas = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        self.labelMapas.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelMapas.setFont(font)
        self.labelMapas.setStyleSheet("font-size: 14pt;\n"
"color:white;\n"
"background-color: #EF8903;\n"
"padding: 0 12px;\n"
"border-radius: 12px;\n"
"max-height: 32px;")
        self.labelMapas.setText("")
        self.labelMapas.setObjectName("labelMapas")
        self.horizontalLayout_6.addWidget(self.labelMapas)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.btnMapas = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnMapas.setFont(font)
        self.btnMapas.setStyleSheet("QPushButton{\n"
"background-color: #BABABA;\n"
"padding: 5px;\n"
"max-width: 150px;\n"
"border-style: outset;\n"
"border-radius: 15px;\n"
"color:  #373737;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #878787;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #121212;\n"
"    color: white;\n"
"}\n"
"\n"
"")
        self.btnMapas.setObjectName("btnMapas")
        self.verticalLayout_7.addWidget(self.btnMapas)
        self.ContVerticalLayout.addWidget(self.MapasWidget)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnComenzar = QtWidgets.QPushButton(self.Container)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btnComenzar.setFont(font)
        self.btnComenzar.setStyleSheet("QPushButton{\n"
"background-color: #EF8903;\n"
"padding: 7px;\n"
"max-width: 160px;\n"
"border-style: outset;\n"
"border-radius: 16px;\n"
"color:  white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #C57000;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #A96000;\n"
"    color: white;\n"
"}\n"
"\n"
"")
        self.btnComenzar.setObjectName("btnComenzar")
        self.horizontalLayout_3.addWidget(self.btnComenzar)
        self.ContVerticalLayout.addLayout(self.horizontalLayout_3)
        self.ContVerticalLayout.setStretch(0, 1)
        self.ContVerticalLayout.setStretch(1, 5)
        self.ContVerticalLayout.setStretch(2, 5)
        self.ContVerticalLayout.setStretch(3, 5)
        self.ContVerticalLayout.setStretch(4, 2)
        self.verticalLayout_4.addLayout(self.ContVerticalLayout)
        self.verticalLayout_3.addWidget(self.Container)

        self.retranslateUi(ArchivosForm)
        QtCore.QMetaObject.connectSlotsByName(ArchivosForm)

    def retranslateUi(self, ArchivosForm):
        _translate = QtCore.QCoreApplication.translate
        ArchivosForm.setWindowTitle(_translate("ArchivosForm", "Form"))
        self.Titulo.setText(_translate("ArchivosForm", "Planeación"))
        self.TituloDatosPrincipales.setText(_translate("ArchivosForm", "Datos Principales (Datos de Alumnos)"))
        self.btnDatosPrincipales.setText(_translate("ArchivosForm", "Agregar +"))
        self.TituloDatosPrincipales_5.setText(_translate("ArchivosForm", "Datos Adicionales (Prerequisitos y Materias por cuatri)"))
        self.btnDatosAdicionales.setText(_translate("ArchivosForm", "Agregar +"))
        self.TituloDatosPrincipales_6.setText(_translate("ArchivosForm", "Mapas Curriculares"))
        self.btnMapas.setText(_translate("ArchivosForm", "Agregar +"))
        self.btnComenzar.setText(_translate("ArchivosForm", "Comenzar"))
