# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ResultadosForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ResultadosForm(object):
    def setupUi(self, ResultadosForm):
        ResultadosForm.setObjectName("ResultadosForm")
        ResultadosForm.resize(803, 600)
        self.centralwidget = QtWidgets.QWidget(ResultadosForm)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.gruposTab = QtWidgets.QWidget()
        self.gruposTab.setMinimumSize(QtCore.QSize(772, 0))
        self.gruposTab.setObjectName("gruposTab")
        self.gridLayout = QtWidgets.QGridLayout(self.gruposTab)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.GruposTreeView = QtWidgets.QTreeView(self.gruposTab)
        self.GruposTreeView.setObjectName("GruposTreeView")
        self.verticalLayout_3.addWidget(self.GruposTreeView)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.gruposTab, "")
        self.alumnosTab = QtWidgets.QWidget()
        self.alumnosTab.setObjectName("alumnosTab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.alumnosTab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.AlumnosTreeView = QtWidgets.QTreeView(self.alumnosTab)
        self.AlumnosTreeView.setObjectName("AlumnosTreeView")
        self.verticalLayout_4.addWidget(self.AlumnosTreeView)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.alumnosTab, "")
        self.materiasTab = QtWidgets.QWidget()
        self.materiasTab.setObjectName("materiasTab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.materiasTab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.MateriasTreeView = QtWidgets.QTreeView(self.materiasTab)
        self.MateriasTreeView.setObjectName("MateriasTreeView")
        self.verticalLayout_5.addWidget(self.MateriasTreeView)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.materiasTab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        ResultadosForm.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ResultadosForm)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 803, 25))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        ResultadosForm.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ResultadosForm)
        self.statusbar.setObjectName("statusbar")
        ResultadosForm.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(ResultadosForm)
        self.toolBar.setObjectName("toolBar")
        ResultadosForm.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExportar = QtWidgets.QAction(ResultadosForm)
        self.actionExportar.setObjectName("actionExportar")
        self.actionGuardar = QtWidgets.QAction(ResultadosForm)
        self.actionGuardar.setObjectName("actionGuardar")
        self.menuArchivo.addAction(self.actionGuardar)
        self.menuArchivo.addAction(self.actionExportar)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.toolBar.addAction(self.actionGuardar)
        self.toolBar.addAction(self.actionExportar)

        self.retranslateUi(ResultadosForm)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ResultadosForm)

    def retranslateUi(self, ResultadosForm):
        _translate = QtCore.QCoreApplication.translate
        ResultadosForm.setWindowTitle(_translate("ResultadosForm", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gruposTab), _translate("ResultadosForm", "Grupos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.alumnosTab), _translate("ResultadosForm", "Alumnos"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.materiasTab), _translate("ResultadosForm", "Materias"))
        self.menuArchivo.setTitle(_translate("ResultadosForm", "Archivo"))
        self.toolBar.setWindowTitle(_translate("ResultadosForm", "toolBar"))
        self.actionExportar.setText(_translate("ResultadosForm", "Exportar"))
        self.actionGuardar.setText(_translate("ResultadosForm", "Guardar"))
