# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FileChoose.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ArchivosForm(object):
    def setupUi(self, ArchivosForm):
        ArchivosForm.setObjectName("ArchivosForm")
        ArchivosForm.resize(711, 540)
        ArchivosForm.setStyleSheet("QVBoxLayout{\n"
"    background-color: #7D211A;\n"
"}")
        self.Container = QtWidgets.QFrame(ArchivosForm)
        self.Container.setGeometry(QtCore.QRect(20, 20, 671, 501))
        self.Container.setStyleSheet("QFrame#Container{\n"
"    background-color: #7D211A;\n"
"    border-radius: 10px;\n"
"}")
        self.Container.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Container.setObjectName("Container")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.Container)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(19, 19, 631, 461))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Titulo = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(26)
        self.Titulo.setFont(font)
        self.Titulo.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Titulo.setStyleSheet("color: white;")
        self.Titulo.setAlignment(QtCore.Qt.AlignCenter)
        self.Titulo.setObjectName("Titulo")
        self.verticalLayout.addWidget(self.Titulo)
        self.widget = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget.setObjectName("widget")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.widget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(1, 9, 631, 87))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.TituloDatosPrincipales = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TituloDatosPrincipales.sizePolicy().hasHeightForWidth())
        self.TituloDatosPrincipales.setSizePolicy(sizePolicy)
        self.TituloDatosPrincipales.setBaseSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.TituloDatosPrincipales.setFont(font)
        self.TituloDatosPrincipales.setStyleSheet("color: white;")
        self.TituloDatosPrincipales.setObjectName("TituloDatosPrincipales")
        self.verticalLayout_2.addWidget(self.TituloDatosPrincipales)
        self.ArchivosPrincipales = QtWidgets.QWidget(self.verticalLayoutWidget_2)
        self.ArchivosPrincipales.setObjectName("ArchivosPrincipales")
        self.verticalLayout_2.addWidget(self.ArchivosPrincipales)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: #BABABA;\n"
"padding: 5px;\n"
"max-width: 150px;\n"
"border-style: outset;\n"
"border-radius: 15px;\n"
"color:  #373737;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #878787;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #121212;\n"
"    color: white;\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.widget_2)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(1, 9, 631, 87))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.TituloDatosPrincipales_5 = QtWidgets.QLabel(self.verticalLayoutWidget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TituloDatosPrincipales_5.sizePolicy().hasHeightForWidth())
        self.TituloDatosPrincipales_5.setSizePolicy(sizePolicy)
        self.TituloDatosPrincipales_5.setBaseSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.TituloDatosPrincipales_5.setFont(font)
        self.TituloDatosPrincipales_5.setStyleSheet("color: white;")
        self.TituloDatosPrincipales_5.setObjectName("TituloDatosPrincipales_5")
        self.verticalLayout_6.addWidget(self.TituloDatosPrincipales_5)
        self.archivosAdicionales = QtWidgets.QWidget(self.verticalLayoutWidget_6)
        self.archivosAdicionales.setObjectName("archivosAdicionales")
        self.verticalLayout_6.addWidget(self.archivosAdicionales)
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"background-color: #BABABA;\n"
"padding: 5px;\n"
"max-width: 150px;\n"
"border-style: outset;\n"
"border-radius: 15px;\n"
"color:  #373737;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #878787;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #121212;\n"
"    color: white;\n"
"}\n"
"\n"
"")
        self.pushButton_5.setObjectName("pushButton_5")
        self.verticalLayout_6.addWidget(self.pushButton_5)
        self.verticalLayout.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.widget_3)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(1, 9, 631, 91))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.verticalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.TituloDatosPrincipales_6 = QtWidgets.QLabel(self.verticalLayoutWidget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TituloDatosPrincipales_6.sizePolicy().hasHeightForWidth())
        self.TituloDatosPrincipales_6.setSizePolicy(sizePolicy)
        self.TituloDatosPrincipales_6.setBaseSize(QtCore.QSize(0, 10))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.TituloDatosPrincipales_6.setFont(font)
        self.TituloDatosPrincipales_6.setStyleSheet("color: white;")
        self.TituloDatosPrincipales_6.setObjectName("TituloDatosPrincipales_6")
        self.verticalLayout_7.addWidget(self.TituloDatosPrincipales_6)
        self.ArchivosMapas = QtWidgets.QWidget(self.verticalLayoutWidget_7)
        self.ArchivosMapas.setObjectName("ArchivosMapas")
        self.verticalLayout_7.addWidget(self.ArchivosMapas)
        self.pushButton_6 = QtWidgets.QPushButton(self.verticalLayoutWidget_7)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background-color: #BABABA;\n"
"padding: 5px;\n"
"max-width: 150px;\n"
"border-style: outset;\n"
"border-radius: 15px;\n"
"color:  #373737;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #878787;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #121212;\n"
"    color: white;\n"
"}\n"
"\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.verticalLayout_7.addWidget(self.pushButton_6)
        self.verticalLayout.addWidget(self.widget_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnComenzar = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.btnComenzar.setFont(font)
        self.btnComenzar.setStyleSheet("QPushButton{\n"
"background-color: #EF8903;\n"
"padding: 5px;\n"
"max-width: 150px;\n"
"border-style: outset;\n"
"border-radius: 15px;\n"
"color:  white;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: #C57000;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: #A96000;\n"
"    color: white;\n"
"}\n"
"\n"
"")
        self.btnComenzar.setObjectName("btnComenzar")
        self.horizontalLayout_3.addWidget(self.btnComenzar)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout.setStretch(0, 5)
        self.verticalLayout.setStretch(1, 10)
        self.verticalLayout.setStretch(2, 10)
        self.verticalLayout.setStretch(3, 10)
        self.verticalLayout.setStretch(4, 6)

        self.retranslateUi(ArchivosForm)
        QtCore.QMetaObject.connectSlotsByName(ArchivosForm)

    def retranslateUi(self, ArchivosForm):
        _translate = QtCore.QCoreApplication.translate
        ArchivosForm.setWindowTitle(_translate("ArchivosForm", "Form"))
        self.Titulo.setText(_translate("ArchivosForm", "Planeación"))
        self.TituloDatosPrincipales.setText(_translate("ArchivosForm", "Datos Principales (Datos de Alumnos)"))
        self.pushButton.setText(_translate("ArchivosForm", "Agregar +"))
        self.TituloDatosPrincipales_5.setText(_translate("ArchivosForm", "Datos Adicionales (Prerequisitos y Materias por cuatri)"))
        self.pushButton_5.setText(_translate("ArchivosForm", "Agregar +"))
        self.TituloDatosPrincipales_6.setText(_translate("ArchivosForm", "Mapas Curriculares"))
        self.pushButton_6.setText(_translate("ArchivosForm", "Agregar +"))
        self.btnComenzar.setText(_translate("ArchivosForm", "Comenzar"))
